categories = {
  'Network Stereo Zone Amplifier',
  'Network Stereo Receiver',
  'Portable Player',
  'Media Player',
  'Network Streamer',
  'Network player & Preamplifier',
  'CD Player',
  'Speaker',
  'DAC',
  'CD player',
  'Streaming DAC',
  'DAC & Network Streamer',
  'DAC & Headphone Amp',
  'Network Audio & CD Player',
  'All-in-One',
  'Wireless speakers & Sound Hub',
  'CD & Digital Player',
  'Home Automation',
  'All-In-One Music Player',
  'DACs & Network Player',
  'Network Audio Transport',
  'Portable DAC',
  'Control Amplifier',
  'Pre-amplifier',
  'Network Player &USB DAC',
  'Integrated Amplifier',
  'Super Audio CD player',
  'Music Server & Streamer',
  'All-in-One Music Player',
  'All-in-One HD Hi-Fi Music Player',
  'Soundbar',
  'Network Audio Player',
  'Compact Portable Player',
  'Network Audio Receiver',
  'Network Streamer &CD Player',
  'Reference-level Music Server & DAC',
  'Network Adapter & DAC',
  'Streaming Transport',
  'Network Streamer & DAC',
  'Super Audio CD Player',
  'Network Streamer & Music Server',
  'Network CD Receiver',
  'Mini-Streamer',
  'Digital Music Server'
}


ingore_categories = {
  'Onkyo Granbeat',
}